# Generated by Django 3.0.8 on 2020-07-14 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.DateField()),
                ('duration', models.DurationField()),
                ('artists', models.ManyToManyField(to='backend.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('playlist_name', models.CharField(max_length=50)),
                ('playlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.DurationField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('playlist_songs', models.ManyToManyField(to='backend.Song')),
            ],
        ),
    ]
