# Generated by Django 3.0.8 on 2020-07-14 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('album_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='playlist_songs',
            new_name='songs',
        ),
        migrations.AddField(
            model_name='playlist',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(default='21', on_delete=django.db.models.deletion.PROTECT, to='backend.Album'),
            preserve_default=False,
        ),
    ]
