# Generated by Django 3.0.8 on 2020-07-14 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200714_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='year',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
