# Generated by Django 3.0.8 on 2020-07-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200714_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DurationField(default=0),
        ),
    ]
