# Generated by Django 3.0.8 on 2020-07-14 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200714_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='artist_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='playlist_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='song_id',
            new_name='id',
        ),
    ]
