# Generated by Django 3.0.8 on 2020-07-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20200714_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='playlist_name',
            new_name='name',
        ),
    ]
