# Generated by Django 3.0.8 on 2020-07-14 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20200714_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='backend.Artist'),
            preserve_default=False,
        ),
    ]
